using VoiceLab.Audio;

namespace VoiceLab.Tests;

public sealed class AudioLifecycleTests
{
    [Fact]public async Task StartWhenStoppedTransitionsToRunning(){var lifecycle=new EngineLifecycleCoordinator();Assert.True(await lifecycle.StartAsync(_=>Task.CompletedTask,()=>Task.CompletedTask));Assert.Equal(AudioEngineState.Running,lifecycle.State);}
    [Fact]public async Task StartWhileRunningDoesNotCreateAnotherSession(){var lifecycle=new EngineLifecycleCoordinator();var starts=0;await lifecycle.StartAsync(_=>{starts++;return Task.CompletedTask;},()=>Task.CompletedTask);Assert.False(await lifecycle.StartAsync(_=>{starts++;return Task.CompletedTask;},()=>Task.CompletedTask));Assert.Equal(1,starts);}
    [Fact]public async Task StopWhenRunningCleansUpOnce(){var lifecycle=new EngineLifecycleCoordinator();var cleanup=0;await lifecycle.StartAsync(_=>Task.CompletedTask,()=>Task.CompletedTask);await lifecycle.StopAsync(()=>{cleanup++;return Task.CompletedTask;});Assert.Equal(AudioEngineState.Stopped,lifecycle.State);Assert.Equal(1,cleanup);}
    [Fact]public async Task StopWhenStoppedIsHarmless(){var lifecycle=new EngineLifecycleCoordinator();var cleanup=0;await lifecycle.StopAsync(()=>{cleanup++;return Task.CompletedTask;});Assert.Equal(0,cleanup);}
    [Fact]public async Task StopDuringStartupCancelsAndCleansUp(){var lifecycle=new EngineLifecycleCoordinator();var cleanup=0;var start=lifecycle.StartAsync(token=>Task.Delay(Timeout.Infinite,token),()=>{cleanup++;return Task.CompletedTask;});await WaitFor(()=>lifecycle.State==AudioEngineState.Starting);await lifecycle.StopAsync(()=>{cleanup++;return Task.CompletedTask;});Assert.False(await start);Assert.Equal(AudioEngineState.Stopped,lifecycle.State);Assert.Equal(1,cleanup);}
    [Fact]public async Task StartupFailureCleansUpAndFaults(){var lifecycle=new EngineLifecycleCoordinator();var cleanup=0;await Assert.ThrowsAsync<InvalidOperationException>(()=>lifecycle.StartAsync(_=>Task.FromException(new InvalidOperationException()),()=>{cleanup++;return Task.CompletedTask;}));Assert.Equal(AudioEngineState.Faulted,lifecycle.State);Assert.Equal(1,cleanup);}
    [Fact]public async Task DeviceLossCleansUpAndAllowsStopRecovery(){var lifecycle=new EngineLifecycleCoordinator();await lifecycle.StartAsync(_=>Task.CompletedTask,()=>Task.CompletedTask);await lifecycle.FaultAsync(new IOException("lost"),()=>Task.CompletedTask);Assert.Equal(AudioEngineState.Faulted,lifecycle.State);await lifecycle.StopAsync(()=>Task.CompletedTask);Assert.Equal(AudioEngineState.Stopped,lifecycle.State);}
    [Fact]public async Task HundredFakeEndpointCyclesReleaseEveryResource(){var lifecycle=new EngineLifecycleCoordinator();var created=0;var disposed=0;FakeEndpoint? endpoint=null;for(var i=0;i<100;i++){Assert.True(await lifecycle.StartAsync(_=>{endpoint=new FakeEndpoint(()=>Interlocked.Increment(ref disposed));Interlocked.Increment(ref created);return Task.CompletedTask;},()=>{endpoint?.Dispose();endpoint=null;return Task.CompletedTask;}));await lifecycle.StopAsync(()=>{endpoint?.Dispose();endpoint=null;return Task.CompletedTask;});}Assert.Equal(AudioEngineState.Stopped,lifecycle.State);Assert.Equal(100,created);Assert.Equal(created,disposed);}
    [Fact]public async Task ConcurrentStartsInvokeFakeEndpointFactoryOnce(){var lifecycle=new EngineLifecycleCoordinator();var starts=0;var gate=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var attempts=Enumerable.Range(0,25).Select(_=>lifecycle.StartAsync(async token=>{Interlocked.Increment(ref starts);await gate.Task.WaitAsync(token);},()=>Task.CompletedTask)).ToArray();await WaitFor(()=>lifecycle.State==AudioEngineState.Starting);gate.SetResult();await Task.WhenAll(attempts);Assert.Equal(1,starts);await lifecycle.StopAsync(()=>Task.CompletedTask);}
    private sealed class FakeEndpoint(Action disposed):IDisposable{private readonly Timer _timer=new(_=>{},null,0,10);private int _disposed;public void Dispose(){if(Interlocked.Exchange(ref _disposed,1)!=0)return;_timer.Dispose();disposed();}}
    private static async Task WaitFor(Func<bool> condition){for(var i=0;i<100&&!condition();i++)await Task.Delay(5);Assert.True(condition());}
}
