using VoiceLab.Audio;
using NAudio.Wave;

namespace VoiceLab.Tests;

public sealed class RecordingPipelineTests
{
    [Fact]public void DefaultFolderPreservesLegacyLocalAppDataPath(){var expected=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"LocalVoiceChanger","Recordings");Assert.Equal(expected,new VoiceLab.Infrastructure.ApplicationSettings().RecordingFolder);}
    [Fact]public void FilenamesAreCollisionProof(){WithDirectory(directory=>{var time=new DateTime(2026,7,18,14,30,52,123);var first=RecordingPipeline.CreateUniquePath(directory,time);File.WriteAllText(first,"");var second=RecordingPipeline.CreateUniquePath(directory,time);Assert.NotEqual(first,second);Assert.EndsWith("-1.wav",second);});}
    [Fact]public async Task PauseExcludesAudioFromDurationAndResumeContinuesSameFile(){await WithDirectoryAsync(async directory=>{await using var pipeline=new RecordingPipeline();var path=await pipeline.StartAsync(directory,WaveFormat.CreateIeeeFloatWaveFormat(48000,1));pipeline.TryEnqueue(new float[480]);pipeline.Pause();pipeline.TryEnqueue(new float[4800]);pipeline.Resume();pipeline.TryEnqueue(new float[480]);await pipeline.StopAsync();Assert.Equal(path,pipeline.FilePath);Assert.InRange(pipeline.RecordedDuration.TotalMilliseconds,19,21);});}
    [Fact]public async Task QueueIsBoundedAndOverflowDoesNotBlockProducer(){await WithDirectoryAsync(async directory=>{await using var pipeline=new RecordingPipeline(2,TimeSpan.FromMilliseconds(100));await pipeline.StartAsync(directory,WaveFormat.CreateIeeeFloatWaveFormat(48000,1));var started=DateTime.UtcNow;for(var i=0;i<20;i++)pipeline.TryEnqueue(new float[480]);var producerTime=DateTime.UtcNow-started;Assert.Equal(2,pipeline.QueueCapacity);Assert.True(pipeline.DroppedBuffers>0);Assert.True(producerTime<TimeSpan.FromMilliseconds(100));await pipeline.StopAsync();});}
    [Fact]public async Task StopFinalizesReadableWav(){await WithDirectoryAsync(async directory=>{await using var pipeline=new RecordingPipeline();var path=await pipeline.StartAsync(directory,WaveFormat.CreateIeeeFloatWaveFormat(48000,1));pipeline.TryEnqueue(new float[480]);await pipeline.StopAsync();using var reader=new WaveFileReader(path);Assert.Equal(48000,reader.WaveFormat.SampleRate);Assert.True(reader.Length>0);});}
    [Fact]public async Task ShutdownDisposeFinalizesWav(){await WithDirectoryAsync(async directory=>{var pipeline=new RecordingPipeline();var path=await pipeline.StartAsync(directory,WaveFormat.CreateIeeeFloatWaveFormat(44100,1));pipeline.TryEnqueue(new float[441]);await pipeline.DisposeAsync();using var reader=new WaveFileReader(path);Assert.True(reader.Length>0);});}
    [Fact]public async Task DoubleStartAndDoubleStopAreIdempotent(){await WithDirectoryAsync(async directory=>{await using var pipeline=new RecordingPipeline();var first=await pipeline.StartAsync(directory,WaveFormat.CreateIeeeFloatWaveFormat(48000,1));var second=await pipeline.StartAsync(directory,WaveFormat.CreateIeeeFloatWaveFormat(48000,1));Assert.Equal(first,second);await pipeline.StopAsync();await pipeline.StopAsync();Assert.Equal(RecordingState.Stopped,pipeline.State);});}
    [Fact]public async Task InvalidRecordingPathFailsWithoutCreatingWriter(){var path=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"),"file-as-directory");Directory.CreateDirectory(Path.GetDirectoryName(path)!);File.WriteAllText(path,"x");await using var pipeline=new RecordingPipeline();await Assert.ThrowsAnyAsync<IOException>(()=>pipeline.StartAsync(path,WaveFormat.CreateIeeeFloatWaveFormat(48000,1)));Directory.Delete(Path.GetDirectoryName(path)!,true);}
    [Fact]public async Task RecordingRejectsRelativeAndNetworkDirectoriesBeforeCreatingFiles(){await using var pipeline=new RecordingPipeline();var format=WaveFormat.CreateIeeeFloatWaveFormat(48000,1);await Assert.ThrowsAsync<ArgumentException>(()=>pipeline.StartAsync(@"relative\recordings",format));await Assert.ThrowsAsync<ArgumentException>(()=>pipeline.StartAsync(@"\\server\share\recordings",format));}
    private static void WithDirectory(Action<string> test){var directory=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));Directory.CreateDirectory(directory);try{test(directory);}finally{Directory.Delete(directory,true);}}
    private static async Task WithDirectoryAsync(Func<string,Task> test){var directory=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));Directory.CreateDirectory(directory);try{await test(directory);}finally{Directory.Delete(directory,true);}}
}
